CREATE TABLE BUYER(
B_ID	VARCHAR2(30)	PRIMARY KEY,
B_PASS	VARCHAR2(100)	NOT NULL,
B_NAME	VARCHAR2(30)	NOT NULL,
B_EMAIL	VARCHAR2(50)	NOT NULL,
B_DATE	DATE			NOT NULL,
B_PHONE	NUMBER,
B_ADDRESS	VARCHAR2(50) UNIQUE ,
B_GENDER VARCHAR2(3) NOT NULL,
B_ACCOUNTNUM VARCHAR2(20) ,
B_MILEAGE	NUMBER
)

drop table buyer;
SELECT * FROM BUYER;  