CREATE TABLE CART(
C_ID VARCHAR2(10) ,
C_COUNT NUMBER	,
C_CODE	VARCHAR2(10) ,
C_PRICE	NUMBER,
C_GPRICE	NUMBER	,
C_NAME	VARCHAR2(100) 
)


SELECT * FROM CART;
DROP TABLE cart   CASCADE CONSTRAINTS;