CREATE TABLE CART(
C_ID VARCHAR2(10) REFERENCES BUYER(B_ID),
C_COUNT NUMBER	NOT NULL,
C_CODE	VARCHAR2(10) 	REFERENCES PRODUCT(P_CODE),
C_PRICE	NUMBER	REFERENCES PRODUCT(P_PRICE),
C_GPRICE	NUMBER	REFERENCES PRODUCT(P_GPRICE),
C_NAME	VARCHAR2(100) REFERENCES PRODUCT(P_NAME)
)


SELECT * FROM CART;