CREATE TABLE PAYMENT(

P_ID VARCHAR2(20) REFERENCES BUYER(B_ID),

P_CODE VARCHAR2(20) NOT NULL REFERENCES PRODUCT(P_CODE),
P_COUNT NUMBER(10)  ,
P_MILEAGE NUMBER NOT NULL,
P_DELIVERY NUMBER NOT NULL,
P_ADDRESS VARCHAR2(30) REFERENCES BUYER(B_ADDRESS)
)