CREATE TABLE PAYMENT(

P_ID VARCHAR2(20) REFERENCES BUYER(B_ID),

P_CODE VARCHAR2(20) REFERENCES PRODUCT(P_CODE),
P_COUNT NUMBER(10) primary key,
P_MILEAGE NUMBER NOT NULL,
P_DELIVERY NUMBER NOT NULL,
P_ADDRESS VARCHAR2(30) REFERENCES BUYER(B_ADDRESS)
)

SELECT * FROM PAYMENT;